# GoldenAppleControl by Terrobility
# Made with loads of love (and maybe a bit of salt)! <3
#
# x=x=x=x=x=x=x=x=x
# | CONFIGURATION |
# x=x=x=x=x=x=x=x=x
# Please don't change the config version.
config-version: 8

plugin-messages:
    no-permission: "&7[&eGolden&6Apple&fControl&7] &cYou don't have permission."
    # Shows remaining time when a player has "goldenapplecontrol.use" permission node and does "/gapple".
    # You can use any placeholders you've registered from below, as long as you have PlaceholderAPI.
    remaining-time:
        - "&c&l&oNOTE: These placeholders won't be replaced unless you have PlaceholderAPI!"
        - "&5\u2588\u2588\u2588\u2588&e\u2588\u2588&5\u2588\u2588"
        - "&5\u2588\u2588\u2588\u2588&e\u2588&5\u2588\u2588\u2588 &6Golden apple&7:"
        - "&5\u2588\u2588&6\u2588\u2588\u2588\u2588&5\u2588\u2588 &c%goldenapplecontrol_gapple%"
        - "&5\u2588&6\u2588\u2588&f\u2588&6\u2588\u2588\u2588&5\u2588"
        - "&5\u2588&6\u2588&f\u2588&6\u2588\u2588\u2588\u2588&5\u2588"
        - "&5\u2588&6\u2588\u2588\u2588\u2588\u2588\u2588&5\u2588 &eEnchanted golden apple&7:"
        - "&5\u2588&6\u2588\u2588\u2588\u2588\u2588\u2588&5\u2588 &c%goldenapplecontrol_enchantedgapple%"
        - "&5\u2588\u2588&6\u2588\u2588\u2588\u2588&5\u2588\u2588"

items:
    whatever-you-want:
        material: GOLDEN_APPLE
        data: 0
        permission: "goldenapplecontrol.randomperm"
        cooldown:
            enabled: true
            duration: 30
            use-formatted-time: true
            use-expired-message: true
            consume-message:
            - "&7You can't eat another &6golden apple&7 for &c%TIME%&7."
            - "&2Purchase a rank at &astore.examplecraft.com &2to bypass cooldowns!"
            cooldown-message:
            - "&7Wait &c%TIME%&7 before eating another &6golden apple&7!"
            expired-message:
            - "&7You may now eat another &6golden apple&7."
        placeholder:
            enabled: true
            # In this case it would be {goldenapplecontrol_gapple} with Maxim or %goldenapplecontrol_gapple% with Clip.
            register-this: "gapple"
        consumption-control:
            enabled: true
            # The food level is measured in half-shanks in the hunger bar. Whole numbers please.
            food-level: 4
            saturation: 9.6
            # TYPE:DURATION(TICKS):AMPLIFIER(LEVEL-1)
            # A list of types can be found here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/potion/PotionEffectType.html
            # e.g. REGENERATION:20:2 would give the player regeneration for 1 second (20 ticks). It would be level 3 because the amplifier = level minus one.
            effects:
            - ABSORPTION:2400:0
            - REGENERATION:100:1

    make-sure-its-not-already-used:
        material: GOLDEN_APPLE
        data: 1
        permission: "idont.reallycare.anymore"
        cooldown:
            enabled: true
            duration: 30
            use-formatted-time: true
            use-expired-message: true
            consume-message:
            - "&7You can't eat another &eenchanted golden apple&7 for &c%TIME%&7."
            - "&2Purchase a rank at &astore.examplecraft.com &2to bypass cooldowns!"
            cooldown-message:
            - "&7Wait &c%TIME%&7 before eating another &eenchanted golden apple&7!"
            expired-message:
            - "&7You may now eat another &eenchanted golden apple&7."
        placeholder:
            enabled: true
            register-this: "enchantedgapple"
        consumption-control:
            enabled: true
            food-level: 4
            saturation: 9.6
            effects:
                - ABSORPTION:2400:0
                - REGENERATION:600:4
                - DAMAGE_RESISTANCE:6000:0
                - FIRE_RESISTANCE:6000:0

    why-not-lol:
        material: COOKED_BEEF
        data: 0
        consumption-control:
            enabled: true
            food-level: 8
            saturation: 12.8
            effects:
                - SPEED:2400:1
                - JUMP:800:2
